<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-18CQLR4" ignored="0" name="FirefoxTest" tests="10" failures="1" timestamp="17 dic 2018 20:59:41 GMT" time="837.045" errors="0">
  <testcase name="authenticationAdmin" time="10.205" classname="infoColeTest.ComentarioTest"/>
  <testcase name="authenticationUser" time="9.578" classname="infoColeTest.ComentarioTest"/>
  <testcase name="authenticationUserWithoutEmail" time="2.799" classname="infoColeTest.ComentarioTest"/>
  <testcase name="authenticationUserWithoutUserName" time="2.736" classname="infoColeTest.ComentarioTest"/>
  <testcase name="createNews" time="15.639" classname="infoColeTest.ComentarioTest"/>
  <testcase name="deleteUser" time="6.803" classname="infoColeTest.ComentarioTest"/>
  <testcase name="createComments" time="13.887" classname="infoColeTest.ComentarioTest"/>
  <testcase name="deleteComment" time="7.877" classname="infoColeTest.ComentarioTest">
    <failure type="java.lang.AssertionError" message="expected [usuario6VDy comentario de prueba Editado] but found [usuario6VDy comentario de prueba]">
      <![CDATA[java.lang.AssertionError: expected [usuario6VDy comentario de prueba Editado] but found [usuario6VDy comentario de prueba]
	at infoColeTest.ComentarioTest.deleteComment(ComentarioTest.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- deleteComment -->
  <testcase name="editComment" time="14.583" classname="infoColeTest.ComentarioTest"/>
  <testcase name="editNews" time="15.314" classname="infoColeTest.ComentarioTest"/>
</testsuite> <!-- FirefoxTest -->
